api_version: 1
handlers: 
  - 
    script: app.app
    url: /.*
runtime: python27
threadsafe: true
version: 1
libraries:
- name: ssl
  version: latest
env_variables:
  PUSHER_APP_ID: 'YOUR PUSHER_APP_ID'
  PUSHER_APP_KEY: 'YOUR PUSHER_APP_KEY'
  PUSHER_APP_SECRET: 'YOUR PUSHER_APP_KEY'
